import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { LuMenu, LuPackage2, LuSearch, LuUserCircle } from 'react-icons/lu';

import { Sidebar } from '@/components/sidebar/Sidebar';
import { Button } from '@/components/ui/button';
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { Sheet, SheetTrigger } from '@/components/ui/sheet';
import './globals.css';
import { MobileSidebar } from '@/components/sidebar/MobileSidebar';
import Image from 'next/image';

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={cn('min-h-screen bg-background font-sans antialiased', inter.variable)}>
				<div className='grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]'>
					<div className='hidden border-r bg-muted/40 md:block'>
						<div className='flex h-full max-h-screen flex-col gap-2'>
							<div className='flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6'>
								<Link href='/' className='flex items-center gap-2 font-semibold'>
									<LuPackage2 className='h-6 w-6' />
									<span className=''>POP App</span>
								</Link>
							</div>
							<Sidebar />
						</div>
					</div>
					<div className='flex flex-col'>
						<header className='flex h-14 items-center gap-4 border-b bg-muted/40 px-4 lg:h-[60px] lg:px-6'>
							<Sheet>
								<SheetTrigger asChild>
									<Button variant='outline' size='icon' className='shrink-0 md:hidden'>
										<LuMenu className='h-5 w-5' />
										<span className='sr-only'>Toggle navigation menu</span>
									</Button>
								</SheetTrigger>
								<MobileSidebar />
							</Sheet>
							<div className='w-full flex-1'>
								<form>
									<div className='relative'>
										<LuSearch className='absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground' />
										<Input
											type='search'
											placeholder='Search products...'
											className='w-full appearance-none bg-background pl-8 shadow-none md:w-2/3 lg:w-1/3'
										/>
									</div>
								</form>
							</div>
							<DropdownMenu>
								<DropdownMenuTrigger asChild>
									<Button variant='secondary' size='icon' className='rounded-full'>
										<Image
											className='h-5 w-5 rounded-full'
											src='https://images.unsplash.com/photo-1542909168-82c3e7fdca5c'
											alt='User Avatar'
											width={60}
											height={60}
										/>
										<span className='sr-only'>Toggle user menu</span>
									</Button>
								</DropdownMenuTrigger>
								<DropdownMenuContent align='end'>
									<DropdownMenuLabel>My Account</DropdownMenuLabel>
									<DropdownMenuSeparator />
									<DropdownMenuItem>Settings</DropdownMenuItem>
									<DropdownMenuItem>Support</DropdownMenuItem>
									<DropdownMenuSeparator />
									<DropdownMenuItem>Logout</DropdownMenuItem>
								</DropdownMenuContent>
							</DropdownMenu>
						</header>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
